import {test} from 'node:test';
import assert from 'node:assert/strict';
import {freshAccount,buy,settle,withdraw,creditOrder,DAY,OFFSET} from '../shared/domain.js';
const start=Date.parse('2026-09-19T18:20:00Z');
test('₹500 plan pays ₹50 at IST midnight, catches up missed days, and caps at ₹1000',()=>{
 const u=freshAccount('test@gmail.com','Test');u.wallet=50000;buy(u,'piano-500',start,'buy-1');
 assert.equal(u.wallet,0);assert.equal(settle(u,start),false);
 const midnight=Date.parse('2026-09-19T18:30:00Z');settle(u,midnight-1);assert.equal(u.wallet,0);settle(u,midnight);assert.equal(u.wallet,5000);
 settle(u,midnight);assert.equal(u.wallet,5000);settle(u,midnight+30*DAY);assert.equal(u.wallet,100000);assert.equal(u.totalEarned,100000);assert.equal(u.investments[0].paidDays,20);settle(u,midnight+60*DAY);assert.equal(u.wallet,100000);
});
test('Insufficient balance and unknown plan do not debit wallet',()=>{const u=freshAccount('a@gmail.com','A');u.wallet=40000;assert.throws(()=>buy(u,'piano-500'),/too low/);assert.throws(()=>buy(u,'bad'),/not found/);assert.equal(u.wallet,40000);assert.equal(u.investments.length,0);});
test('Duplicate purchase request only creates one investment',()=>{const u=freshAccount('a@gmail.com','A');u.wallet=100000;buy(u,'piano-500',start,'same');buy(u,'piano-500',start,'same');assert.equal(u.wallet,50000);assert.equal(u.investments.length,1);});
test('Withdrawal minimum, reservation and duplicate protection',()=>{const u=freshAccount('a@gmail.com','A');u.wallet=100000;assert.throws(()=>withdraw(u,49900,{name:'Test',accountNumber:'12345678901',ifsc:'HDFC0001234'}),/Minimum/);assert.throws(()=>withdraw(u,50000,{name:'Test',accountNumber:'12345678901',ifsc:'invalid'}),/IFSC/);withdraw(u,50000,{name:'Test',accountNumber:'12345678901',ifsc:'HDFC0001234'},start,'req1');withdraw(u,50000,{name:'Test',accountNumber:'12345678901',ifsc:'HDFC0001234'},start,'req1');assert.equal(u.wallet,50000);assert.equal(u.withdrawals.length,1);assert.equal(u.withdrawals[0].status,'pending');assert.throws(()=>withdraw(u,60000,{name:'Test',accountNumber:'12345678901',ifsc:'HDFC0001234'}),/Insufficient/);});
test('Captured Razorpay payment credits once and validates exact amount and currency',()=>{const u=freshAccount('a@gmail.com','A');u.orders.push({id:'order_one',amount:50000,credited:false});const p={id:'pay_one',order_id:'order_one',amount:50000,currency:'INR',status:'captured'};assert.throws(()=>creditOrder(u,'order_one',{...p,status:'authorized'}));assert.throws(()=>creditOrder(u,'order_one',{...p,amount:100}));assert.throws(()=>creditOrder(u,'order_one',{...p,currency:'USD'}));assert.equal(u.wallet,0);assert.equal(creditOrder(u,'order_one',p),true);assert.equal(creditOrder(u,'order_one',p),false);assert.equal(u.wallet,50000);assert.equal(u.transactions.length,1);});
test('VIP sample plan pays higher income and stops at its cap',()=>{const u=freshAccount('a@gmail.com','A');u.wallet=500000;buy(u,'vip-5000',start);settle(u,start+25*DAY);assert.equal(u.wallet,1500000);assert.equal(u.investments[0].paidDays,20);});
