import BottomNav from '../components/BottomNav';
import { useAuth } from '../context/AuthContext';
import { useNavigate } from 'react-router-dom';

const features = [
  { icon: '☀️', title: 'Clean Solar Energy',  desc: 'Invest directly into real-world solar grid & rooftop infrastructure projects.' },
  { icon: '⚡', title: 'Guaranteed Power Yield',desc: 'Earn high daily returns generated by round-the-clock green power production.' },
  { icon: '🌙', title: 'Daily Midnight Power',desc: 'Daily power generation profits credited automatically to your wallet every night.' },
  { icon: '🔋', title: 'VIP Mega Grids',      desc: 'High-capacity industrial solar stations yielding accelerated returns for elite partners.' },
  { icon: '🏦', title: 'Fast Bank Withdrawals',desc: 'Direct payout to your Bank Account or UPI ID anytime (Minimum ₹1,000).' },
  { icon: '🤝', title: 'Green Referral Bonus', desc: 'Invite friends to join and both receive instant ₹100 cash rewards.' },
];

const stats = [
  { value: '50K+',  label: 'Solar Investors' },
  { value: '₹4.5Cr+', label: 'Green Payouts' },
  { value: '60 Days', label: 'Cycle Period' },
  { value: '4.9★',  label: 'Trust Score' },
];

const steps = [
  { step: '01', title: 'Recharge Energy Wallet', desc: 'Add investment capital securely via GPay, PhonePe, Paytm, or UPI QR.', icon: '💳', color: '#D97706', bg: '#FEF3C7' },
  { step: '02', title: 'Select Solar Plan',      desc: 'Choose your solar capacity from ₹500 (Solar Spark) to ₹50,000 (VIP Megawatt Empire).', icon: '☀️', color: '#EA580C', bg: '#FFEDD5' },
  { step: '03', title: 'Daily Power Earnings',   desc: 'Your solar units produce power daily and credit returns every midnight.', icon: '⚡', color: '#059669', bg: '#D1FAE5' },
  { step: '04', title: 'Withdraw Profits',       desc: 'Cash out your accumulated green energy profits into your Bank or UPI.', icon: '🏦', color: '#2563EB', bg: '#DBEAFE' },
];

export default function HomePage() {
  const { user }   = useAuth();
  const navigate   = useNavigate();

  return (
    <div className="min-h-screen bg-slate-50 pb-28 overflow-x-hidden text-slate-800">

      {/* ── Hero ─────────────────────────────────────────── */}
      <div
        className="relative px-5 pt-12 pb-14 text-center overflow-hidden border-b border-amber-200/50"
        style={{ background: 'linear-gradient(180deg, #FEF3C7 0%, #FFFBEB 60%, #F8FAFC 100%)' }}
      >
        {/* Soft sun rays glow */}
        <div className="absolute top-0 right-0 w-64 h-64 rounded-full pointer-events-none"
             style={{ background: 'radial-gradient(circle, rgba(245, 158, 11, 0.18), transparent 70%)', transform: 'translate(20%, -20%)' }} />
        <div className="absolute bottom-0 left-0 w-52 h-52 rounded-full pointer-events-none"
             style={{ background: 'radial-gradient(circle, rgba(249, 115, 22, 0.12), transparent 70%)', transform: 'translate(-20%, 20%)' }} />

        <div className="relative z-10">
          {/* Solar Icon Badge */}
          <div
            className="w-20 h-20 rounded-3xl mx-auto mb-3 flex items-center justify-center text-4xl shadow-xl border border-amber-200"
            style={{ background: 'linear-gradient(135deg, #F59E0B 0%, #D97706 100%)' }}
          >
            ☀️
          </div>

          <div className="inline-flex items-center gap-1.5 px-3 py-1 rounded-full bg-amber-100 border border-amber-300 text-[11px] font-bold text-amber-800 mb-2 shadow-sm">
            <span>⚡</span> RENEWABLE SOLAR ENERGY · GUARANTEED DAILY RETURNS
          </div>

          <h1 className="text-4xl font-black text-slate-900 tracking-tight">SolarWealth</h1>
          <p className="text-slate-600 text-sm mt-1.5">
            Welcome, Solar Partner <span className="font-bold text-amber-700">{user?.name || user?.email?.split('@')[0]}</span>!
          </p>
          <p className="text-slate-500 text-xs mt-1 max-w-xs mx-auto">
            Harness the power of the sun. Invest in solar grids & earn guaranteed daily power dividends.
          </p>

          <button
            onClick={() => navigate('/plans')}
            className="mt-6 inline-flex items-center gap-2 bg-gradient-to-r from-amber-500 via-orange-500 to-amber-600 text-white font-extrabold text-sm px-7 py-3.5 rounded-2xl shadow-lg shadow-orange-500/25 hover:shadow-xl hover:scale-105 transition-all"
          >
            <span>☀️</span> Explore Solar Plans
          </button>
        </div>
      </div>

      {/* ── Solar Energy Power Cells Banner ─────────────── */}
      <div className="mx-4 -mt-5 relative z-10">
        <div
          className="rounded-2xl p-2.5 flex justify-between items-center shadow-lg border border-amber-200 bg-white"
        >
          {['500W', '1kW', '2.5kW', '5kW', '10kW', '20kW', '50kW'].map((cell, i) => (
            <div
              key={i}
              onClick={() => navigate('/plans')}
              className="flex-1 mx-0.5 py-3 rounded-xl text-center cursor-pointer transition-all hover:bg-amber-50 active:scale-95 border border-slate-100 bg-slate-50"
            >
              <span className="text-[10px] font-black text-amber-700 block">{cell}</span>
              <p className="text-[8px] text-emerald-600 font-bold">60D ROI</p>
            </div>
          ))}
        </div>
      </div>

      {/* ── Floating Stats Card ────────────────────────── */}
      <div className="mx-4 mt-4">
        <div
          className="rounded-2xl p-4 grid grid-cols-4 divide-x divide-slate-100 bg-white border border-slate-200/80 shadow-sm"
        >
          {stats.map((s) => (
            <div key={s.label} className="text-center px-1">
              <p className="text-amber-600 font-black text-sm">{s.value}</p>
              <p className="text-slate-400 text-[10px] font-semibold mt-0.5">{s.label}</p>
            </div>
          ))}
        </div>
      </div>

      {/* ── About SolarWealth ──────────────────────────── */}
      <div className="mx-4 mt-6">
        <div
          className="rounded-2xl p-5 border border-amber-200/80 bg-white shadow-sm"
          style={{ background: 'linear-gradient(135deg, #FFFFFF 0%, #FFFBEB 100%)' }}
        >
          <div className="flex items-center gap-2 mb-2">
            <span className="text-2xl">🌍</span>
            <h2 className="text-lg font-bold text-slate-900">About SolarWealth</h2>
          </div>
          <p className="text-slate-600 text-xs leading-relaxed">
            SolarWealth is India's pioneer in community-funded solar energy development. We channel everyday retail investments into industrial solar rooftops, utility-scale photovoltaic panels, and clean energy storage grids.
          </p>
          <p className="text-slate-600 text-xs leading-relaxed mt-2">
            Power generated by your funded solar panels is sold back to national grids and commercial hubs, delivering guaranteed <strong className="text-amber-700">High Total Returns</strong> (e.g., ₹500 investment yields ₹100/day for 60 days = ₹6,000 total) credited directly to your wallet every single night!
          </p>
          <div className="mt-3 grid grid-cols-2 gap-2 pt-2.5 border-t border-amber-100 text-[11px] text-slate-700">
            <div className="flex items-center gap-1.5">
              <span className="text-amber-600 font-bold">✓</span> 60 Days Guaranteed Payouts
            </div>
            <div className="flex items-center gap-1.5">
              <span className="text-amber-600 font-bold">✓</span> Daily Midnight Grid Credits
            </div>
            <div className="flex items-center gap-1.5">
              <span className="text-amber-600 font-bold">✓</span> Instant Bank & UPI Cashouts
            </div>
            <div className="flex items-center gap-1.5">
              <span className="text-amber-600 font-bold">✓</span> Real-World Green Asset Backing
            </div>
          </div>
        </div>
      </div>

      {/* ── How It Works (Solar Cycle) ────────────────── */}
      <div className="mx-4 mt-6">
        <h2 className="text-base font-bold text-slate-900 mb-3 flex items-center gap-2">
          <span className="w-1.5 h-5 rounded-full bg-amber-500 block" />
          How The Solar Cycle Works
        </h2>
        <div className="space-y-3">
          {steps.map((item) => (
            <div
              key={item.step}
              className="flex items-center gap-4 rounded-xl p-4 border border-slate-200/80 bg-white hover:border-amber-300 shadow-sm transition-all"
            >
              <div
                className="w-11 h-11 rounded-xl flex items-center justify-center text-xl flex-shrink-0"
                style={{ background: item.bg, border: `1px solid ${item.color}33` }}
              >
                {item.icon}
              </div>
              <div className="flex-1">
                <h3 className="text-slate-900 font-bold text-sm">{item.title}</h3>
                <p className="text-slate-500 text-xs mt-0.5">{item.desc}</p>
              </div>
              <div
                className="text-xs font-black"
                style={{ color: item.color }}
              >
                {item.step}
              </div>
            </div>
          ))}
        </div>
      </div>

      {/* ── Why Choose Us ─────────────────────────────── */}
      <div className="mx-4 mt-6">
        <h2 className="text-base font-bold text-slate-900 mb-3 flex items-center gap-2">
          <span className="w-1.5 h-5 rounded-full bg-orange-500 block" />
          Solar Energy Advantages
        </h2>
        <div className="grid grid-cols-2 gap-3">
          {features.map((f) => (
            <div
              key={f.title}
              className="rounded-xl p-4 border border-slate-200/80 bg-white hover:border-amber-300 shadow-sm transition-all"
            >
              <span className="text-2xl">{f.icon}</span>
              <h3 className="text-slate-900 font-bold text-xs mt-2 mb-1">{f.title}</h3>
              <p className="text-slate-500 text-[11px] leading-relaxed">{f.desc}</p>
            </div>
          ))}
        </div>
      </div>

      {/* ── Live Payment & Withdrawal Proofs (Trust Section) ── */}
      <div className="mx-4 mt-7">
        <div className="flex items-center justify-between mb-3">
          <div className="flex items-center gap-2">
            <span className="w-1.5 h-5 rounded-full bg-emerald-500 block" />
            <h2 className="text-base font-bold text-slate-900">Live Solar Withdrawal Proofs</h2>
          </div>
          <span className="flex items-center gap-1.5 text-[11px] font-bold text-emerald-700 bg-emerald-50 px-2.5 py-1 rounded-full border border-emerald-200">
            <span className="w-1.5 h-1.5 rounded-full bg-emerald-500 animate-ping" />
            100% Verified
          </span>
        </div>
        <p className="text-slate-500 text-xs mb-3">Recent solar energy dividend payouts credited directly to users' Bank & UPI accounts.</p>

        {/* Proof Cards */}
        <div className="space-y-3">
          {[
            {
              name: 'Rahul V.',
              phone: '+91 98765*****',
              bank: 'State Bank of India',
              upi: 'rahul****@okhdfcbank',
              amount: '₹7,500.00',
              plan: '☀️ Solar Panel 2500 (60D)',
              time: '12 mins ago',
              refNo: 'UPI/426789123456',
              app: 'GPay',
              appBg: 'bg-blue-50 text-blue-700 border-blue-200'
            },
            {
              name: 'Pooja Sharma',
              phone: '+91 87654*****',
              bank: 'HDFC Bank Ltd',
              upi: 'pooja****@ybl',
              amount: '₹15,000.00',
              plan: '☀️ Solar Grid 5000 (60D)',
              time: '34 mins ago',
              refNo: 'IMPS/426899452101',
              app: 'PhonePe',
              appBg: 'bg-purple-50 text-purple-700 border-purple-200'
            },
            {
              name: 'Amit Patel',
              phone: '+91 91234*****',
              bank: 'Punjab National Bank',
              upi: 'amit****@paytm',
              amount: '₹30,000.00',
              plan: '☀️ Solar Station 10000 (60D)',
              time: '1 hour ago',
              refNo: 'RTGS/PNB499120489',
              app: 'Paytm',
              appBg: 'bg-sky-50 text-sky-700 border-sky-200'
            },
            {
              name: 'Vikram Singh',
              phone: '+91 70123*****',
              bank: 'ICICI Bank',
              upi: 'vikram****@icici',
              amount: '₹3,000.00',
              plan: '☀️ Solar Ray 1000 (60D)',
              time: '2 hours ago',
              refNo: 'UPI/426987110943',
              app: 'BHIM',
              appBg: 'bg-emerald-50 text-emerald-700 border-emerald-200'
            },
          ].map((proof, idx) => (
            <div
              key={idx}
              className="rounded-2xl p-4 border border-slate-200/80 bg-white relative overflow-hidden shadow-sm hover:border-amber-300 transition-all"
            >
              <div className="flex items-start justify-between mb-2">
                <div className="flex items-center gap-2.5">
                  <div className="w-9 h-9 rounded-full bg-emerald-50 border border-emerald-200 flex items-center justify-center text-emerald-600 font-black text-sm">
                    ✓
                  </div>
                  <div>
                    <h4 className="text-slate-900 font-bold text-sm flex items-center gap-1.5">
                      {proof.name}
                      <span className="text-[10px] font-normal text-slate-400">({proof.phone})</span>
                    </h4>
                    <p className="text-slate-500 text-[11px]">{proof.bank}</p>
                  </div>
                </div>
                <div className="text-right">
                  <span className={`text-xs px-2.5 py-0.5 rounded-md font-bold border ${proof.appBg}`}>
                    {proof.app}
                  </span>
                  <p className="text-slate-400 text-[10px] mt-1">{proof.time}</p>
                </div>
              </div>

              <div className="bg-slate-50 rounded-xl p-3 border border-slate-200/60 my-2 flex items-center justify-between">
                <div>
                  <span className="text-slate-400 text-[10px] uppercase font-semibold tracking-wider block">Credited to A/C</span>
                  <span className="text-emerald-600 font-black text-lg tracking-tight">{proof.amount}</span>
                </div>
                <div className="text-right">
                  <span className="text-[10px] text-slate-400 block">From Plan</span>
                  <span className="text-amber-700 font-bold text-xs">{proof.plan}</span>
                </div>
              </div>

              <div className="flex items-center justify-between text-[10px] text-slate-400 pt-1 border-t border-slate-100">
                <span>Ref: <span className="text-slate-600 font-mono">{proof.refNo}</span></span>
                <span className="text-emerald-600 font-semibold flex items-center gap-1">
                  <span className="w-1.5 h-1.5 rounded-full bg-emerald-500 inline-block" />
                  Bank Transfer Successful
                </span>
              </div>
            </div>
          ))}
        </div>

        <div className="mt-3.5 bg-emerald-50 border border-emerald-200 rounded-xl p-3 text-center">
          <p className="text-emerald-800 text-xs font-bold">🛡️ 100% Guaranteed Solar Dividend Returns</p>
          <p className="text-emerald-600 text-[10px] mt-0.5 font-medium">Automated payouts directly to your verified Bank Account / UPI ID</p>
        </div>
      </div>

      {/* ── Call to Action ────────────────────────────── */}
      <div className="mx-4 mt-6 mb-4">
        <button
          onClick={() => navigate('/plans')}
          className="w-full rounded-2xl p-5 text-center border border-amber-200 bg-white hover:border-amber-400 shadow-sm transition-all"
        >
          <span className="text-3xl block mb-1">☀️</span>
          <p className="text-slate-900 font-extrabold text-base">Start Your Solar Investment Today</p>
          <p className="text-amber-600 text-xs font-bold mt-1">Select from ₹500 up to ₹50,000 · Guaranteed 60-Day Profits</p>
        </button>
      </div>

      <BottomNav />
    </div>
  );
}
