import React,{useState,useEffect,useRef} from 'react';
import {createRoot} from 'react-dom/client';
import {ArrowUpRight,ArrowDownLeft,ArrowRight,Plus,Wallet,House,LayoutGrid,UserRound,ChevronRight,ShieldCheck,Clock3,TrendingUp,Check,Copy,LogOut,Crown,RefreshCw,X,Eye,EyeOff,Music2,Info,LoaderCircle,CheckCircle2} from 'lucide-react';
import {api} from './api';
import {plans,istDay,DAY,OFFSET,MIN_WITHDRAWAL} from '../shared/domain';
import './style.css';
import PolicyNotice from './PolicyNotice';
import OwnerPortal from './OwnerPortal';
import {RechargeForm,RechargeHistory} from './Payments';
const money=n=>new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:0}).format(n/100);
const photo='https://images.unsplash.com/photo-1681417738609-d5469c22a9d6?auto=format&fit=crop&w=1600&h=900&q=85';
function Logo({owner=false}){return <a className="logo" href={owner?'/owner':'/#home'} aria-label={owner?'Piano Wealth owner dashboard':'Piano Wealth home'}><span className="logomark"><i/><i/><i/></span>piano<span className="logo-wealth">wealth</span></a>;}
function App(){
 const [policyAccepted,setPolicyAccepted]=useState(false);
 const [user,setUser]=useState(null),[config,setConfig]=useState(null),[loading,setLoading]=useState(true),[page,setPage]=useState(location.hash.slice(1)||'home'),[notice,setNotice]=useState(''),[modal,setModal]=useState(null),[tab,setTab]=useState('standard'),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const [amount,setAmount]=useState('1000'),[withdrawMethod,setWithdrawMethod]=useState('bank'),[upi,setUpi]=useState(''),[bankName,setBankName]=useState(''),[accountNumber,setAccountNumber]=useState(''),[confirmAccount,setConfirmAccount]=useState(''),[ifsc,setIfsc]=useState(''),[withdrawPassword,setWithdrawPassword]=useState('');const dialog=useRef(null),returnFocus=useRef(null),operation=useRef('');
 function navigate(p){location.hash=p;setPage(p);window.scrollTo({top:0,behavior:'smooth'});}
 useEffect(()=>{const f=()=>setPage(location.hash.slice(1)||'home');window.addEventListener('hashchange',f);window.addEventListener('popstate',f);api('/config').then(setConfig).then(()=>api('/me')).then(d=>{setUser(d.user);setPolicyAccepted(!!d.policyAcknowledged);}).catch(e=>{if(e.message!=='Please log in.')setError(e.message);}).finally(()=>setLoading(false));return()=>{window.removeEventListener('hashchange',f);window.removeEventListener('popstate',f);};},[]);
 useEffect(()=>{if(!user)return;const timer=setInterval(()=>api('/me').then(d=>{setUser(d.user);setPolicyAccepted(!!d.policyAcknowledged);}).catch(()=>{}),30000);return()=>clearInterval(timer);},[!!user]);
 useEffect(()=>{if(!notice)return;const t=setTimeout(()=>setNotice(''),5000);return()=>clearTimeout(t);},[notice]);
 useEffect(()=>{if(modal){returnFocus.current=document.activeElement;dialog.current?.showModal();}else{dialog.current?.close();returnFocus.current?.focus();}},[modal]);
 useEffect(()=>{
  if(!user)return;
  const isOwnerPath=location.pathname.replace(/\/$/,'')==='/owner';
  if(user.isOwner){
   if(!isOwnerPath||(location.hash&&location.hash!=='#privacy')){history.replaceState(null,'','/owner');setPage('owner');}
  }else if(isOwnerPath||page==='owner'){history.replaceState(null,'','/#home');setPage('home');}
 },[user?.isOwner,!!user,page]);
 async function logout(){try{await api('/logout',{});await api('/config').then(setConfig);setUser(null);setPolicyAccepted(false);setError('');}catch(e){setError(e.message);}}
 const ownerEntry=location.pathname.replace(/\/$/,'')==='/owner'||page==='owner';
 const active=user?.investments.filter(p=>p.earned<p.total)||[];
 const daily=active.reduce((s,p)=>s+p.daily,0),invested=user?.investments.reduce((s,p)=>s+p.price,0)||0;
 function open(m){operation.current=crypto.randomUUID();setError('');setAmount(m==='withdraw'?String(MIN_WITHDRAWAL/100):'1000');setWithdrawPassword('');setModal(m);}
 async function action(route,body,success){setBusy(true);setError('');try{const d=await api(route,body);if(d.user)setUser(d.user);setModal(null);setNotice(success);return true;}catch(e){setError(e.message);return false;}finally{setBusy(false);}}
 if(loading)return <div className="loading"><Logo/><LoaderCircle className="spin"/>Loading your workspace…</div>;
 if(page==='privacy')return <PolicyNotice readOnly onBack={()=>{if(user?.isOwner){history.replaceState(null,'','/owner');setPage('owner');}else navigate(user?'profile':'home');}}/>;
 if(!user)return <Auth ownerOnly={ownerEntry} config={config} initialError={error} onLogin={u=>{setPolicyAccepted(false);setUser(u);setError('');if(u.isOwner){history.replaceState(null,'','/owner');setPage('owner');}else{history.replaceState(null,'','/#home');setPage('home');}}}/>;
 const policyPopup=!policyAccepted?<PolicyNotice popup onAccepted={()=>setPolicyAccepted(true)} onLogout={logout}/>:null;
 if(user.isOwner)return <div className="owner-app">{policyPopup}<a href="#owner-main" className="skip">Skip to dashboard</a><header className="owner-header"><Logo owner/><div className="owner-account"><span><b>Owner workspace</b><small>{user.email}</small></span><button className="button outline" onClick={()=>navigate('privacy')}>Privacy notice</button><button className="button outline" onClick={logout}><LogOut size={17}/>Log out</button></div></header><main id="owner-main" tabIndex={-1} className="owner-main">{error&&<Error text={error}/>}<OwnerPortal/></main><footer className="owner-footer">Piano Wealth · Owner administration</footer></div>;
 return <>{policyPopup}<a href="#main" className="skip" onClick={e=>{e.preventDefault();document.getElementById('main').focus();}}>Skip to content</a><header className="header"><div className="header-inner"><Logo/><span className="header-caption">A little every day. A rhythm of growth.</span><div className="header-right"><span className="account-badge">Investment workspace</span><button className="avatar" onClick={()=>navigate('profile')} aria-label="Open profile">{user.name.slice(0,1).toUpperCase()}</button></div></div></header>
 <main id="main" className="main" tabIndex={-1}>
 {page==='home'&&<><div className="page-heading"><div><p className="eyebrow">YOUR DAILY OVERTURE</p><h1>Welcome, {user.name.split(' ')[0]} <span className="handwave">✦</span></h1><p>Let’s make every day count.</p></div><span className="date"><Clock3 size={15}/>{new Date().toLocaleDateString('en-IN',{day:'numeric',month:'short',year:'numeric'})}</span></div>
 <div className="home-top"><section className="hero"><img src={photo} alt="Polished grand piano keys in soft light"/><div className="hero-shade"/><div className="hero-content"><span className="hero-label"><Music2 size={14}/> WELCOME TO PIANO WEALTH</span><h2>Small beginnings.<br/>A greater <em>tomorrow.</em></h2><p>Explore a plan, follow your daily progress,<br className="desktop"/> and keep everything in one place.</p><button className="button light" onClick={()=>navigate('plans')}>Explore plans <ArrowUpRight size={18}/></button></div><div className="hero-counter"><span>01</span> / 01</div></section>
 <section className="balance-card"><div className="section-row"><span className="muted">Available balance</span><Wallet size={21}/></div><strong className="balance">{money(user.wallet)}</strong><span className="small muted">Your wallet</span><div className="balance-actions"><button className="button" onClick={()=>open('recharge')}><Plus size={17}/> Add money</button><button className="button outline" onClick={()=>open('withdraw')}><ArrowUpRight size={17}/> Withdraw</button></div><div className="wallet-foot"><ShieldCheck size={15}/><span>Recharge first. Choose your plan next.</span></div></section></div>
 <div className="stats"><Stat icon={TrendingUp} label="Total earned" value={money(user.totalEarned)} detail="All-time plan earnings"/><Stat icon={LayoutGrid} label="Active plans" value={String(active.length).padStart(2,'0')} detail={active.length?'Growing at your pace':'Your next chapter awaits'}/><Stat icon={Clock3} label="Daily income" value={money(daily)} detail="Credited at midnight · IST"/><Stat icon={Wallet} label="Total invested" value={money(invested)} detail="Across all your plans"/></div>
 <div className="section-heading"><div><p className="eyebrow">FIND YOUR RHYTHM</p><h2>A plan for every beginning.</h2></div><button className="text-button" onClick={()=>navigate('plans')}>View all plans <ArrowRight size={17}/></button></div>
 <div className="plan-grid home-plans">{plans.slice(0,3).map((p,i)=><Plan key={p.id} p={p} index={i} onBuy={()=>open(p)}/>)}</div>
 <section className="how"><div><p className="eyebrow">SIMPLE FROM THE START</p><h2>Your journey, in three notes.</h2></div>{[['01','Add to your wallet','Recharge your wallet to get started.'],['02','Choose your plan','Find the right starting point for you.'],['03','Follow your progress','Track daily credits in your wallet.']].map(([n,t,d])=><div className="how-step" key={n}><span>{n}</span><div><h3>{t}</h3><p>{d}</p></div></div>)}</section></>}
 {page==='plans'&&<><PageTitle eyebrow="SET YOUR PACE" title="Find your next note." subtitle="Choose a plan and follow its daily progress."/><div className="plans-toolbar"><div className="tabs" aria-label="Plan categories">{[['standard','Piano plans'],['vip','VIP plans'],['active','My plans']].map(([v,label])=><button key={v} className={tab===v?'selected':''} onClick={()=>setTab(v)} aria-pressed={tab===v}>{v==='vip'&&<Crown size={16}/>} {label}{v==='active'&&<span className="count">{user.investments.length}</span>}</button>)}</div><span className="muted small">Wallet balance <b>{money(user.wallet)}</b></span></div>
 {tab==='active'?<div className="active-grid">{user.investments.length?user.investments.slice().reverse().map(p=><article className="active-card" key={p.id}><div className="section-row"><span className="plan-icon"><Music2/></span><span className="pill">{p.earned>=p.total?'Completed':'Active'}</span></div><h2>{p.name}</h2><p className="muted">{money(p.price)} plan · {money(p.daily)} / day</p><div className="earned-row"><b>{money(p.earned)}</b><span>of {money(p.total)}</span></div><progress value={p.earned} max={p.total}/><div className="section-row small muted"><span>{p.paidDays} of {p.days} credits received</span><span>{Math.round(p.earned/p.total*100)}%</span></div><p className="small">{p.earned>=p.total?'All scheduled credits received.':`Next credit: ${new Date((istDay(Date.now())+1)*DAY-OFFSET).toLocaleString('en-IN',{timeZone:'Asia/Kolkata',day:'numeric',month:'short',hour:'2-digit',minute:'2-digit'})} IST`}</p></article>):<Empty icon={Music2} title="Your first note is waiting." text="Add money and choose a plan to start tracking your progress." action="Explore plans" onClick={()=>setTab('standard')}/>}</div>:<><div className="plan-grid">{plans.filter(p=>p.vip===(tab==='vip')).map((p,i)=><Plan key={p.id} p={p} index={i} onBuy={()=>open(p)}/>)}</div>{tab==='vip'&&<div className="info"><Info size={18}/>VIP plans run for 60 days with 18× total return, including principal. Daily credit is 30% of the plan amount.</div>}</>}
 <div className="info"><Clock3 size={18}/>Daily credits are added at 12:00 AM IST, starting at the next midnight after purchase. Each plan stops at its total return.</div></>}
 {page==='wallet'&&<><PageTitle eyebrow="EVERY RUPEE, IN VIEW" title="Your wallet." subtitle="Add money, manage withdrawals, and follow every transaction."/><div className="wallet-overview"><section className="wallet-main"><span>Available balance</span><h2>{money(user.wallet)}</h2><div className="flex"><button className="button light" onClick={()=>open('recharge')}><Plus size={18}/>Add money</button><button className="button ghost" onClick={()=>open('withdraw')}><ArrowUpRight size={18}/>Withdraw</button></div><p><ShieldCheck size={15}/>Minimum withdrawal {money(MIN_WITHDRAWAL)}</p></section><Stat icon={TrendingUp} label="Total earnings" value={money(user.totalEarned)} detail="Daily credits received"/><Stat icon={Clock3} label="Pending withdrawals" value={money(user.withdrawals.filter(w=>['awaiting_owner','pending','queued','processing','scheduled'].includes(w.status)).reduce((s,w)=>s+w.amount,0))} detail="Reserved from your balance"/></div>{user.withdrawals.length>0&&<section className="withdrawal-history"><h2>Withdrawals</h2>{user.withdrawals.map(w=><article className="withdrawal-item" key={w.id}><div><b>{money(w.amount)}</b><p>{w.bank?.name||'Recipient'} · {w.method==='upi'?w.bank?.upiMasked:`Bank ending ${w.bank?.last4||'—'}`}</p><span>{w.bank?.ifsc}{w.utr?` · UTR: ${w.utr}`:''}</span></div><span className={'payout-status '+w.status}>{w.status==='awaiting_owner'?'Awaiting owner':w.status}</span></article>)}</section>}<RechargeHistory/><section className="transactions"><div className="section-heading"><h2>Transaction history</h2><span className="small muted">{user.transactions.length} transactions</span></div>{user.transactions.length?<div>{user.transactions.map(t=><div className="transaction" key={t.id}><span className={'transaction-icon '+(t.amount>0?'positive':'')}>{t.amount>0?<ArrowDownLeft size={20}/>:<ArrowUpRight size={20}/>}</span><div className="transaction-description"><b>{t.note}</b><span>{new Date(t.at).toLocaleString('en-IN',{timeZone:'Asia/Kolkata',dateStyle:'medium',timeStyle:'short'})} IST</span></div><b className={t.amount>0?'green':''}>{t.amount>0?'+':'−'}{money(Math.abs(t.amount))}</b></div>)}</div>:<Empty icon={Wallet} title="A fresh start." text="Your recharges, purchases, earnings, and withdrawals will appear here." action="Add money" onClick={()=>open('recharge')}/>}</section></>}
 {page==='profile'&&<><PageTitle eyebrow="YOUR PIANO ACCOUNT" title="Made personal." subtitle="Your details, your referrals, your next chapter."/><div className="profile-grid"><section className="profile-card"><div className="big-avatar">{user.name[0].toUpperCase()}</div><h2>{user.name}</h2><p className="muted">{user.email}</p><button className="text-button" onClick={()=>navigate('privacy')}>Risk & privacy notice</button><span className="pill">{user.isOwner?'Owner':'Member'}</span><div className="profile-detail"><span>Account email</span><b>{user.email}</b></div><div className="profile-detail"><span>Email verification</span><b>Not verified</b></div><button className="button outline full" onClick={async()=>{await api('/logout',{});await api('/config').then(setConfig);setUser(null);}}><LogOut size={17}/>Log out</button></section><div><section className="referral-card"><span className="plan-icon"><UserRound/></span><h2>Good things are better shared.</h2><p className="muted">Invite a friend. You both receive ₹250 when they sign up with your code.</p><div className="referral-code"><b>{user.referralCode}</b><button className="icon-button" aria-label="Copy referral code" onClick={()=>navigator.clipboard.writeText(user.referralCode).then(()=>setNotice('Referral code copied.')).catch(()=>setNotice('Select the code and copy it manually.'))}><Copy size={19}/></button></div><p className="small muted">₹250 for you + ₹250 for your friend. Added to both wallets after a successful referral signup.</p></section><div className="info"><Info size={20}/><span>Your recharge is credited after the owner approves your UTR submission. You can then use your wallet to buy a plan.</span></div></div></div></>}
 {!['home','plans','wallet','profile'].includes(page)&&<Empty icon={House} title="Let’s get you back home." text="This page could not be found." action="Go home" onClick={()=>navigate('home')}/>}
 <footer><Logo/><span>Plan returns depend on operator funding.</span><span className="small">{page==='home'?<a href="https://unsplash.com/photos/a-black-and-white-photo-of-a-piano-lU6-LbPvZSg" target="_blank" rel="noreferrer">Photo: Luwadlin Bosman</a>:'Made for your daily rhythm.'}</span></footer>
 </main><nav className="bottom-nav" aria-label="Main navigation">{[['home','Home',House],['plans','Plans',LayoutGrid],['wallet','Wallet',Wallet],['profile','Profile',UserRound]].map(([p,label,Icon])=><button key={p} onClick={()=>navigate(p)} className={page===p?'active':''} aria-current={page===p?'page':undefined}><Icon size={20}/><span>{label}</span>{page===p&&<i/>}</button>)}</nav>
 {notice&&<div className="toast" role="status"><CheckCircle2 size={20}/>{notice}</div>}
 <dialog ref={dialog} onCancel={e=>{if(busy)e.preventDefault();else setModal(null);}} className="modal" aria-label="Wallet and plan actions"><button className="modal-close icon-button" aria-label="Close dialog" disabled={busy} onClick={()=>setModal(null)}><X/></button>
 {modal==='recharge'?<RechargeForm payment={config.qrPayment} onSubmitted={()=>{setModal(null);setNotice('UTR submitted. Your wallet will be credited after owner approval.');navigate('wallet');}}/>:
 modal==='withdraw'?<form onSubmit={e=>{e.preventDefault();if(withdrawMethod==='bank'&&accountNumber!==confirmAccount){setError('Bank account numbers do not match.');return;}action('/wallet/withdraw',{amount:Number(amount)*100,bank:withdrawMethod==='upi'?{method:'upi',name:bankName.trim(),upi:upi.trim()}:{method:'bank',name:bankName.trim(),accountNumber,ifsc:ifsc.toUpperCase()},confirmAccount,password:withdrawPassword,requestId:operation.current},'Withdrawal sent to owner. Funds reserved until the request is processed.');}}><span className="plan-icon"><ArrowUpRight/></span><h2>Request a withdrawal</h2><div className="tabs withdrawal-tabs" aria-label="Withdrawal method"><button type="button" className={withdrawMethod==='bank'?'selected':''} onClick={()=>setWithdrawMethod('bank')}>Bank account</button><button type="button" className={withdrawMethod==='upi'?'selected':''} onClick={()=>setWithdrawMethod('upi')}>UPI</button></div><p className="muted">Available: {money(user.wallet)} · Minimum {money(MIN_WITHDRAWAL)}</p><label>Amount (₹)<input type="number" min={MIN_WITHDRAWAL/100} step="1" value={amount} onChange={e=>setAmount(e.target.value)} required autoFocus/></label><label>Account holder name<input placeholder="Name as shown in your bank account" value={bankName} onChange={e=>setBankName(e.target.value)} minLength="2" maxLength="100" required autoComplete="off"/></label>{withdrawMethod==='bank'?<><label>Bank account number<input inputMode="numeric" pattern="[0-9]{9,18}" placeholder="9–18 digit account number" value={accountNumber} onChange={e=>setAccountNumber(e.target.value.replace(/\D/g,''))} required autoComplete="off"/></label><label>Confirm account number<input inputMode="numeric" pattern="[0-9]{9,18}" value={confirmAccount} onChange={e=>setConfirmAccount(e.target.value.replace(/\D/g,''))} required autoComplete="off"/></label><label>IFSC code<input placeholder="e.g. HDFC0001234" pattern="[A-Z]{4}0[A-Z0-9]{6}" maxLength="11" value={ifsc} onChange={e=>setIfsc(e.target.value.toUpperCase())} required autoComplete="off"/></label></>:<label>UPI ID<input placeholder="yourname@bank" value={upi} onChange={e=>setUpi(e.target.value)} autoComplete="off" maxLength="321" required/></label>}<label>Confirm with your login password<input type="password" autoComplete="current-password" value={withdrawPassword} onChange={e=>setWithdrawPassword(e.target.value)} required/></label><div className="info small">{config?.withdrawRequestsEnabled?'Check the recipient carefully. Your request goes to the owner for review. Automatic bank/UPI transfers are unavailable; the amount stays reserved until resolution or rejection.':'Withdrawals are temporarily unavailable. No funds will be deducted.'}</div><Error text={error}/><button className="button full" disabled={busy}>{busy?'Submitting…':`Confirm withdrawal · ${money(Number(amount)*100)}`}</button></form>:
 modal&&typeof modal==='object'?<div><span className="plan-icon">{modal.vip?<Crown/>:<Music2/>}</span><h2>Start your {modal.name} plan</h2><p className="muted">Review your plan before you begin.</p><div className="purchase-summary">{[['Plan amount',money(modal.price)],['Daily credit',money(modal.daily)],['Duration',`${modal.days} days`],['Total return',money(modal.total)],['Wallet balance',money(user.wallet)]].map(([a,b])=><div className="section-row" key={a}><span>{a}</span><b>{b}</b></div>)}</div><p className="small muted">Total return includes the original plan amount. The first credit arrives at the next midnight IST.</p><Error text={error}/>{user.wallet<modal.price?<button className="button full" onClick={()=>open('recharge')}>Add money to continue <Plus size={17}/></button>:<button className="button full" disabled={busy} onClick={()=>action('/plans/buy',{planId:modal.id,requestId:operation.current},`${modal.name} plan is now active.`)}>{busy?'Activating…':`Confirm purchase · ${money(modal.price)}`}</button>}</div>:null}
 </dialog></>;
}
function Error({text}){return text?<p className="error" role="alert">{text}</p>:null;}
function PageTitle({eyebrow,title,subtitle}){return <div className="page-heading"><div><p className="eyebrow">{eyebrow}</p><h1>{title}</h1><p>{subtitle}</p></div></div>;}
function Stat({icon:Icon,label,value,detail}){return <article className="stat"><span className="stat-icon"><Icon size={19}/></span><span className="muted small">{label}</span><strong>{value}</strong><span className="small muted">{detail}</span></article>;}
function Empty({icon:Icon,title,text,action,onClick}){return <div className="empty"><span className="plan-icon"><Icon/></span><h2>{title}</h2><p className="muted">{text}</p><button className="button outline" onClick={onClick}>{action}<ArrowRight size={17}/></button></div>;}
function Plan({p,index,onBuy}){return <article className={'plan-card '+(p.vip?'vip ':'')+(index===1?'featured':'')}><div className="section-row"><span className="plan-icon">{p.vip?<Crown size={22}/>:<Music2 size={22}/>}</span><span className="plan-type">{p.vip?'VIP COLLECTION':index===1?'POPULAR CHOICE':`PIANO ${String(index+1).padStart(2,'0')}`}</span></div><div className="plan-name"><h3>{p.name}</h3><p>{index===0?'A simple place to start.':index===1?'Find your everyday rhythm.':'Take your next step forward.'}</p></div><div className="plan-price">{money(p.price)}<span> / plan</span></div><div className="plan-details"><div><span>Daily income</span><b>{money(p.daily)}<small>/ day</small></b></div><div><span>Duration</span><b>{p.days} days</b></div></div><div className="plan-total"><span>Total return <small>(incl. principal)</small></span><strong>{money(p.total)}<span>{p.total/p.price}×</span></strong></div><button className={'button full '+(index===1?'':'outline')} onClick={onBuy}>Choose plan <ArrowUpRight size={17}/></button><div className="plan-note"><Clock3 size={13}/>Daily credit at midnight IST</div></article>;}
function Auth({onLogin,config,initialError,ownerOnly=false}){
 const [mode,setMode]=useState(ownerOnly?'login':'signup'),[name,setName]=useState(''),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[referral,setReferral]=useState(''),[error,setError]=useState(initialError),[busy,setBusy]=useState(false),[visible,setVisible]=useState(false),[success,setSuccess]=useState('');
 async function submit(e){e.preventDefault();setBusy(true);setError('');try{if(mode==='signup'){const result=await api('/signup',{name:name.trim(),email:email.trim(),password,referral:referral.trim()});setMode('login');setSuccess(result.referralBonus?'Account created. ₹250 referral bonus added to your wallet. Log in to continue.':'Account created. Log in to start your journey.');setPassword('');}else{const d=await api('/login',{email:email.trim(),password});onLogin(d.user);}}catch(e){setError(e.message);}finally{setBusy(false);}}
 return <div className="auth"><div className="auth-left"><Logo owner={ownerOnly}/><div className="auth-form"><p className="eyebrow">YOUR NEXT CHAPTER STARTS HERE</p><h1>{ownerOnly?'Owner sign in.':mode==='signup'?'A little today.\nMore tomorrow.':'Welcome back.'}</h1><p className="muted">{ownerOnly?'Sign in with your enrolled owner account to manage Piano Wealth.':mode==='signup'?'Create your account and find your rhythm.':'Log in to pick up where you left off.'}</p>{!ownerOnly&&<div className="auth-tabs">{['signup','login'].map(m=><button key={m} onClick={()=>{setMode(m);setError('');setSuccess('');}} className={mode===m?'selected':''}>{m==='signup'?'Create account':'Log in'}</button>)}</div>}<form onSubmit={submit}>{mode==='signup'&&<label>Full name<input autoComplete="name" value={name} onChange={e=>setName(e.target.value)} placeholder="Your name" minLength="2" maxLength="60" required/></label>}<label>Gmail address<input type="email" autoComplete="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="you@gmail.com" required/></label><label>Password<div className="password-field"><input type={visible?'text':'password'} autoComplete={mode==='signup'?'new-password':'current-password'} minLength="8" maxLength="100" value={password} onChange={e=>setPassword(e.target.value)} placeholder="At least 8 characters" required/><button className="icon-button" type="button" aria-label={visible?'Hide password':'Show password'} onClick={()=>setVisible(!visible)}>{visible?<EyeOff size={18}/>:<Eye size={18}/>}</button></div></label>{mode==='signup'&&<label>Referral code <span className="muted">(optional)</span><input value={referral} onChange={e=>setReferral(e.target.value)} placeholder="Enter a friend's code for ₹250 bonus" maxLength="30"/></label>}<Error text={error}/>{success&&<p className="success" role="status">{success}</p>}<button className="button full" disabled={busy||!config}>{busy?<LoaderCircle className="spin" size={18}/>:mode==='signup'?'Create account':'Log in'}<ArrowRight size={18}/></button></form><p className="auth-note"><a href="#privacy">Read the investment risk & privacy notice</a> before adding money.</p></div><p className="auth-footer">© {new Date().getFullYear()} Piano Wealth. Your daily rhythm.</p></div><div className="auth-art"><img src={photo} alt="A grand piano with beautifully lit keys"/><div className="auth-art-overlay"/><span className="art-caption"><Music2 size={16}/> THE PIANO EXPERIENCE</span><div className="art-text"><p>Every great composition<br/>starts with <em>one note.</em></p><span>Your journey starts with a small step.<br/>We help you keep track of every one.</span></div><span className="art-bottom">A LITTLE EVERY DAY.</span></div></div>;
}
createRoot(document.getElementById('root')).render(<App/>);
