import React,{useState,useEffect} from 'react';
import {RefreshCw,Users,Wallet,ArrowUpRight,TrendingUp,Clock3,Search} from 'lucide-react';
import {api} from './api';
import {OwnerReview} from './Payments';
const money=n=>new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:0}).format((n||0)/100);
const date=n=>new Date(n).toLocaleString('en-IN',{timeZone:'Asia/Kolkata',dateStyle:'medium',timeStyle:'short'})+' IST';
const status=s=>s==='awaiting_owner'?'Awaiting owner':s==='pending'?'Queued for payout':s.replaceAll('_',' ');
export default function OwnerPortal(){
 const [tab,setTab]=useState('overview'),[data,setData]=useState(null),[error,setError]=useState(''),[refreshKey,setRefreshKey]=useState(0);
 async function refresh(){try{const d=await api('/owner/analytics');setData(d);setError('');}catch(e){setError(e.message);}}
 useEffect(()=>{refresh();},[refreshKey]);
 const reload=()=>setRefreshKey(k=>k+1);
 const t=data?.totals||{},r=data?.recharges||{};
 return <><div className="page-heading"><div><p className="eyebrow">PIANO WEALTH · OWNER</p><h1>Your business, in view.</h1><p>Review money movement and understand account activity.</p></div><button className="button outline" onClick={reload}><RefreshCw size={17}/>Refresh</button></div><div className="tabs owner-tabs" aria-label="Owner portal sections">{[['overview','Overview'],['withdrawals','Withdrawals'],['recharges','Recharges'],['users','Users']].map(([id,label])=><button key={id} className={tab===id?'selected':''} aria-pressed={tab===id} onClick={()=>setTab(id)}>{label}</button>)}</div>{error&&<p className="error" role="alert">{error}</p>}
 {tab==='overview'&&<>{!data?<p role="status">Loading analytics…</p>:<><p className="muted small">Last updated {date(data.asOf)} · Account ledger totals, not bank balances.</p><div className="owner-stats">{[
 ['Total users',t.totalUsers,'Registered accounts',Users],['Wallet balances',money(t.walletBalance),'Available across all accounts',Wallet],['Verified recharges',money(r.approved?.amount),`${r.approved?.count||0} confirmed payments`,TrendingUp],['Awaiting recharge review',money((r.pending?.amount||0)+(r.approving?.amount||0)),`${(r.pending?.count||0)+(r.approving?.count||0)} submissions`,Clock3],['Pending withdrawals',money(t.pendingWithdrawalAmount),`${t.pendingWithdrawalCount||0} reserved requests`,ArrowUpRight],['Completed payouts',money(t.paidWithdrawals),'Recorded completed transfers',ArrowUpRight],['Active plans',t.activePlans,`${money(t.dailyCredits)} scheduled per day`,TrendingUp],['Total plan credits',money(t.totalEarned),`${money(t.totalInvested)} total plan purchases`,Wallet]
 ].map(([label,value,detail,Icon])=><article className="stat" key={label}><span className="stat-icon"><Icon size={19}/></span><span className="small muted">{label}</span><strong>{value??0}</strong><span className="small muted">{detail}</span></article>)}</div><div className="owner-callout"><div><h2>Withdrawal requests</h2><p>Check the customer, destination and amount when reviewing a withdrawal.</p></div><button className="button" onClick={()=>setTab('withdrawals')}>Review requests<ArrowUpRight size={18}/></button></div></>}{data&&!data.payoutsConfigured&&<div className="info">Automatic payouts are unavailable. Withdrawal requests can be reviewed or rejected; this app does not transfer funds.</div>}</>}
 {tab==='withdrawals'&&<WithdrawalQueue refreshKey={refreshKey} onChange={reload}/>}
 {tab==='recharges'&&<OwnerReview key={refreshKey}/>}
 {tab==='users'&&<UserDirectory refreshKey={refreshKey}/>}
 </>;
}
function Pager({page,pages,total,setPage}){return <div className="owner-pager"><span>{total} records · Page {page} of {Math.max(1,pages)}</span><div className="flex"><button className="button outline" disabled={page<=1} onClick={()=>setPage(page-1)}>Previous</button><button className="button outline" disabled={page>=pages} onClick={()=>setPage(page+1)}>Next</button></div></div>;}
function WithdrawalQueue({refreshKey,onChange}){
 const [view,setView]=useState('pending'),[page,setPage]=useState(1),[data,setData]=useState(null),[error,setError]=useState(''),[notice,setNotice]=useState('');
 useEffect(()=>{let cancelled=false;api(`/owner/withdrawals?view=${view}&page=${page}`).then(d=>{if(!cancelled){setData(d);setError('');}}).catch(e=>{if(!cancelled)setError(e.message);});return()=>{cancelled=true;};},[view,page,refreshKey]);
 return <section><div className="section-heading"><h2>Customer withdrawals</h2><div className="tabs">{[['pending','Awaiting / processing'],['history','History']].map(([id,label])=><button key={id} className={view===id?'selected':''} onClick={()=>{setView(id);setPage(1);setData(null);}}>{label}</button>)}</div></div>{notice&&<p className="success" role="status">{notice}</p>}{error&&<p className="error" role="alert">{error}</p>}{!data&&!error&&<p role="status">Loading requests…</p>}<div className="review-grid">{data?.withdrawals.map(w=><WithdrawalCard key={w.id} w={w} onDone={message=>{setNotice(message);onChange();}}/>)}</div>{data&&!data.withdrawals.length&&<div className="empty"><Clock3/><h2>No requests in this view.</h2></div>}{data&&<Pager {...data} setPage={setPage}/>}</section>;
}
function WithdrawalCard({w,onDone}){
 const [decision,setDecision]=useState('reject'),[note,setNote]=useState(''),[password,setPassword]=useState(''),[confirmed,setConfirmed]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('');
 async function submit(e){e.preventDefault();setBusy(true);setError('');try{const d=await api(`/owner/withdrawals/${w.userId}/${w.id}/review`,{decision,note,password,confirmed});setPassword('');onDone(d.message);}catch(e){setError(e.message);}finally{setBusy(false);}}
 return <article className="review-card"><div className="section-row"><h2>{money(w.amount)}</h2><span className={'payout-status '+w.status}>{status(w.status)}</span></div><p><b>{w.name}</b><br/>{w.email}</p><div className="withdraw-destination"><span>{w.method==='upi'?'UPI transfer':'Bank transfer'}</span><b>{w.bank.name}</b><span>{w.method==='upi'?w.bank.upiMasked:`Account ending ${w.bank.last4} · ${w.bank.ifsc}`}</span></div><p className="small muted">Requested {date(w.at)}<br/>Reference: {w.id}</p>{w.utr&&<p>Transfer UTR: <b>{w.utr}</b></p>}{w.reviewNote&&<p className="small muted">Review: {w.reviewNote}</p>}{w.canReview?<form onSubmit={submit}><label>Action<select value={decision} onChange={e=>setDecision(e.target.value)}><option value="reject">Reject and restore balance</option></select></label><label>Review note<input minLength="5" maxLength="300" value={note} onChange={e=>setNote(e.target.value)} required/></label><label className="checkbox-label"><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)} required/>I confirm rejection and restoration of the reserved balance.</label><label>Owner password<input type="password" autoComplete="current-password" value={password} onChange={e=>setPassword(e.target.value)} required/></label>{error&&<p className="error" role="alert">{error}</p>}<button className="button full" disabled={busy}>{busy?'Processing…':'Reject and restore balance'}</button></form>:<p className="small muted">{w.ownerApprovedAt?`Authorized ${date(w.ownerApprovedAt)}. Automatic reconciliation has stopped; check any previous transfer externally.`:'This request is closed.'}</p>}</article>;
}
function UserDirectory({refreshKey}){
 const [q,setQ]=useState(''),[search,setSearch]=useState(''),[page,setPage]=useState(1),[data,setData]=useState(null),[error,setError]=useState('');
 useEffect(()=>{let cancelled=false;api(`/owner/users?page=${page}&q=${encodeURIComponent(search)}`).then(d=>{if(!cancelled){setData(d);setError('');}}).catch(e=>{if(!cancelled)setError(e.message);});return()=>{cancelled=true;};},[search,page,refreshKey]);
 return <section><div className="section-heading"><h2>User analytics</h2><form className="owner-search" onSubmit={e=>{e.preventDefault();setSearch(q.trim());setPage(1);}}><label className="sr-only" htmlFor="owner-search">Search name or email</label><input id="owner-search" placeholder="Search name or email" maxLength="100" value={q} onChange={e=>setQ(e.target.value)}/><button className="button outline" aria-label="Search users"><Search size={18}/></button></form></div>{error&&<p className="error" role="alert">{error}</p>}<div className="owner-table-wrap"><table className="owner-table"><thead><tr><th>User / joined</th><th>Wallet</th><th>Plan purchases</th><th>Active / daily</th><th>Total earned</th><th>Pending withdrawals</th><th>Paid withdrawals</th></tr></thead><tbody>{data?.users.map(u=><tr key={u.id}><td><b>{u.name}</b><span>{u.email}</span><small>{date(u.createdAt)}</small></td><td>{money(u.wallet)}</td><td>{money(u.totalInvested)}</td><td>{u.activePlans}<span>{money(u.dailyCredits)} / day</span></td><td>{money(u.totalEarned)}</td><td>{money(u.pendingWithdrawals)}</td><td>{money(u.paidWithdrawals)}</td></tr>)}</tbody></table></div>{data&&!data.users.length&&<p className="muted">No users match your search.</p>}{data&&<Pager {...data} setPage={setPage}/>}</section>;
}
